#!/usr/bin/env python3
"""Build a FRESH prompt set from nvidia/Nemotron-Post-Training-Dataset-v2 (non-multilingual).

This is the prompt builder for fresh draws (e.g. the 400K step-4 set): it downloads
the 4 non-multilingual splits (chat/stem/math/code), converts each row to the prompt
schema, dedups to UNIQUE user prompts, selects a capability-weighted 400K via
deterministic md5(uuid) ordering, optionally length-caps, and shuffles — emitting
prompts.jsonl ready for generate_responses.py. No separate sampling step.

NOTE: the pipeline's step-1 corpus (the 220K set) predates this script and is NOT
re-drawable with it (different procedure, multilingual splits included, md5-of-text
ids) — rebuild that one with ``rebuild_prompts_from_manifest.py`` instead.

Selection operates on unique prompts (one md5-lowest representative per distinct user
text), so a category's ceiling is its unique-prompt count, NOT its row count:
  chat 545,844 uniq / stem 355,000 / math 102,616 / code 33,884  (code is 80% dup).
code can't supply 90K, so the default tilts its deficit into stem (which has headroom).

Output schema (one JSON per line) — the input contract of generate_responses.py:
  {"id": <uuid>, "category": "chat|stem|math|code",
   "conversations": [{"role":"system","content":...}, {"role":"user","content":...}],
   "reasoning": "on|off"}   # kept as metadata; NOT used to gate selection

Why these choices (validated against the actual data):
  * non-ML pool = chat 627,720 / stem 355,000 / math 239,467 / code 175,000 = 1,397,187
  * all rows are single-turn [system, user, assistant]; system content is empty
    -> we drop the original assistant (regenerated by a teacher later) and inject
       a default system prompt.
  * `reasoning` describes the ORIGINAL answer's think-trace, not the prompt, so it
    does not change which prompts are worth keeping.
  * md5(uuid)-lowest selection is deterministic + reproducible: raising a per-category
    N yields a superset of a smaller N, and the same prompts are reused for every
    teacher model so generations stay comparable.

Default allocation (capability-weighted, ~75% reasoning-dense skills):
  stem 166116 | math 100000 | code 33884 | chat 100000  = 400000

Example:
  python sample_nemotron.py --output prompts.jsonl \
      --max-prompt-tokens 14336 --tokenizer Qwen/Qwen3.5-4B --shuffle

Iterative rounds: pass a previous generate_responses.py output via --exclude-ids-file
so a new draw never re-picks prompts already generated (ids round-trip unchanged).
"""
import argparse, json, hashlib, os, sys

REPO = "nvidia/Nemotron-Post-Training-Dataset-v2"
SHARDS = {
    "chat": 12, "stem": 2, "math": 2, "code": 2,   # non-multilingual splits only
}
# capped at each split's UNIQUE-prompt supply: code has only 33,884 unique prompts
# (80% dup), math 102,616; stem absorbs the code deficit. See docstring.
DEFAULT_ALLOC = {"stem": 166116, "math": 100000, "code": 33884, "chat": 100000}
DEFAULT_SYSTEM = "You are a helpful assistant."


def md5hex(s: str) -> str:
    return hashlib.md5(s.encode()).hexdigest()


def shard_paths(cat: str, n: int):
    return [f"data/{cat}-{i:05d}-of-{n:05d}.parquet" for i in range(n)]


def load_exclude_ids(files) -> set:
    """Collect top-level ``id`` from prior regen JSONL(s) so a new round never
    re-draws prompts already generated.

    This honours the contract documented in generate_responses.py: its output is
    "directly reusable as the sampler's --exclude-ids-file". ids round-trip
    unchanged (sampler emits uuid -> generate_responses preserves it), so passing
    a previous output file here excludes exactly those prompts.
    """
    ids = set()
    for path in files or []:
        if not os.path.exists(path):
            print(f"  WARNING: --exclude-ids-file not found: {path}", file=sys.stderr)
            continue
        n = 0
        with open(path) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    rid = json.loads(line).get("id")
                except Exception:
                    continue
                if rid is not None:
                    ids.add(str(rid)); n += 1
        print(f"  exclude: {n:,} ids from {path}", file=sys.stderr)
    return ids


def to_prompt(messages):
    """messages[{role,content}] -> [system, user] conversations, assistant dropped.

    Keeps everything up to and including the last user turn; ensures a non-empty
    system message (injects the default if missing/empty)."""
    msgs = list(messages)
    # drop trailing non-user turns (assistant) so the prompt ends on the user
    while msgs and msgs[-1]["role"] != "user":
        msgs.pop()
    if not msgs:
        return None
    conv = []
    has_sys = msgs[0]["role"] == "system" and (msgs[0]["content"] or "").strip()
    if not has_sys:
        conv.append({"role": "system", "content": DEFAULT_SYSTEM})
    for m in msgs:
        if m["role"] == "system" and not (m["content"] or "").strip():
            continue  # skip empty system; default already injected
        conv.append({"role": m["role"], "content": m["content"]})
    # require at least one user turn present
    if not any(m["role"] == "user" for m in conv):
        return None
    return conv


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output", default="prompts.jsonl")
    ap.add_argument("--cache-dir", default=None, help="HF cache dir (default: HF default)")
    ap.add_argument("--alloc", default=None,
                    help="override allocation, e.g. 'stem=110000,math=100000,code=90000,chat=100000'")
    ap.add_argument("--oversample", type=float, default=1.10,
                    help="preselect this fraction extra unique prompts as headroom for "
                         "length-cap drops, then trim to target (clamped by supply)")
    ap.add_argument("--exclude-ids-file", action="append", default=None,
                    help="regen JSONL whose top-level ids are dropped from the pool before "
                         "selection (repeatable). Pass a previous generate_responses.py output "
                         "to never re-draw already-generated prompts across rounds.")
    ap.add_argument("--max-prompt-tokens", type=int, default=0,
                    help="if >0, drop prompts whose chat-template token count >= this "
                         "(prevents prompt+max_tokens>context 400s at generation; needs --tokenizer)")
    ap.add_argument("--tokenizer", default=None,
                    help="HF tokenizer id/path for --max-prompt-tokens, e.g. Qwen/Qwen3.5-4B")
    ap.add_argument("--shuffle", action="store_true",
                    help="shuffle the output (seeded) so categories interleave for the generator")
    ap.add_argument("--seed", type=int, default=0, help="shuffle seed")
    ap.add_argument("--no-download", action="store_true",
                    help="assume shards already cached; skip snapshot_download")
    ap.add_argument("--stats-only", action="store_true",
                    help="print unique-prompt counts + selection per category and exit")
    args = ap.parse_args()
    if args.max_prompt_tokens and not args.tokenizer:
        ap.error("--max-prompt-tokens needs --tokenizer")

    alloc = dict(DEFAULT_ALLOC)
    if args.alloc:
        alloc = {}
        for kv in args.alloc.split(","):
            k, v = kv.split("=")
            alloc[k.strip()] = int(v)
    print(f"target allocation: {alloc}  (total {sum(alloc.values()):,})", file=sys.stderr)

    exclude = load_exclude_ids(args.exclude_ids_file)
    if exclude:
        print(f"  excluding {len(exclude):,} already-generated ids from the pool", file=sys.stderr)

    import pyarrow.parquet as pq
    from huggingface_hub import snapshot_download

    if not args.no_download:
        print("downloading non-multilingual parquet shards (~8GB, resumable)...", file=sys.stderr)
    local = snapshot_download(
        REPO, repo_type="dataset", cache_dir=args.cache_dir,
        allow_patterns=[f"data/{c}-*" for c in SHARDS],
        local_files_only=args.no_download,
    )
    print(f"local snapshot: {local}", file=sys.stderr)

    # ---- pass 1: dedup to UNIQUE user prompts, keeping the md5-lowest uuid as each
    #      one's representative. Selection then runs on unique prompts, so a category's
    #      ceiling is its unique-prompt count (code has only ~34K unique, 80% dup).
    uniq = {c: {} for c in SHARDS}   # cat -> {user_hash: (md5_uuid, uuid)}
    for cat, n in SHARDS.items():
        if alloc.get(cat, 0) <= 0:
            continue
        d = uniq[cat]
        n_rows = n_excl = 0
        for p in shard_paths(cat, n):
            t = pq.read_table(os.path.join(local, p), columns=["uuid", "messages"])
            uu, mm = t.column("uuid").to_pylist(), t.column("messages").to_pylist()
            for u, msgs in zip(uu, mm):
                n_rows += 1
                if u in exclude:
                    n_excl += 1
                    continue
                conv = to_prompt(msgs)
                if conv is None:
                    continue
                uh = md5hex(" ".join(m["content"] for m in conv if m["role"] == "user"))
                h = md5hex(u)
                cur = d.get(uh)
                if cur is None or h < cur[0]:   # deterministic representative per prompt
                    d[uh] = (h, u)
        excl = f", excluded {n_excl:,}" if n_excl else ""
        print(f"  [{cat}] {n_rows:,} rows -> {len(d):,} unique prompts{excl}", file=sys.stderr)

    # select the md5-lowest unique prompts per category, up to target (capped by supply)
    selected = {}   # cat -> set(uuid)
    for cat in SHARDS:
        want = alloc.get(cat, 0)
        if want <= 0:
            continue
        keep = int(want * args.oversample) if args.oversample > 1 else want
        ranked = sorted(uniq[cat].values())           # by md5(uuid)
        selected[cat] = set(u for _, u in ranked[:keep])

    if args.stats_only:
        for cat in SHARDS:
            want = alloc.get(cat, 0)
            short = "  <-- supply < target" if len(uniq[cat]) < want else ""
            print(f"{cat}: {len(uniq[cat]):,} unique | target {want:,} | "
                  f"preselect {len(selected.get(cat, ())):,}{short}")
        return

    # ---- pass 2: fetch messages for the selected uuids (rows are already unique users)
    rows_by_cat = {c: [] for c in SHARDS}  # cat -> [(md5, obj)]
    for cat, n in SHARDS.items():
        sel = selected.get(cat)
        if not sel:
            continue
        for p in shard_paths(cat, n):
            t = pq.read_table(os.path.join(local, p),
                              columns=["uuid", "category", "reasoning", "messages"])
            for r in t.to_pylist():
                u = r["uuid"]
                if u not in sel:
                    continue
                conv = to_prompt(r["messages"])
                if conv is None:
                    continue
                rows_by_cat[cat].append((md5hex(u), {
                    "id": u, "category": r.get("category", cat),
                    "conversations": conv, "reasoning": r.get("reasoning")}))

    # optional length cap (chat-template token count)
    plen = None
    if args.max_prompt_tokens:
        from transformers import AutoTokenizer
        tok = AutoTokenizer.from_pretrained(args.tokenizer, trust_remote_code=True)

        def plen(conv):
            # render then encode: some Qwen tokenizers miscount with tokenize=True
            s = tok.apply_chat_template(conv, add_generation_prompt=True, tokenize=False)
            return len(tok(s, add_special_tokens=False).input_ids)

    # length-cap + trim each category to target (md5-lowest first; already unique)
    out = []                       # held to allow a global shuffle
    n_out = {c: 0 for c in SHARDS}
    n_len = 0
    for cat in SHARDS:
        want = alloc.get(cat, 0)
        for _, obj in sorted(rows_by_cat[cat]):
            if n_out[cat] >= want:
                break
            if plen and plen(obj["conversations"]) >= args.max_prompt_tokens:
                n_len += 1
                continue
            out.append(obj)
            n_out[cat] += 1

    if args.shuffle:
        import random
        random.seed(args.seed)
        random.shuffle(out)        # interleave categories for the generator

    with open(args.output, "w") as o:
        for obj in out:
            o.write(json.dumps(obj, ensure_ascii=False) + "\n")

    print(f"\nwrote {len(out):,} -> {args.output}"
          + (f"  (dropped {n_len:,} over-length)" if plen else ""), file=sys.stderr)
    for c in SHARDS:
        avail, want = len(uniq[c]), alloc.get(c, 0)
        note = ("  <-- supply < target" if n_out[c] < want and avail <= want else
                "  <-- SHORT (raise --oversample)" if n_out[c] < want else "")
        print(f"  {c}: {n_out[c]:,} / {want:,}{note}", file=sys.stderr)


if __name__ == "__main__":
    main()
